on:
  push:
    tags-ignore:
      - '*'
    branches:
      - '*'
  pull_request:
    branches:
      - '!staging'
      - '!development'
jobs:
  echo:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: echo
        run: echo "hello world"
